### ISSUE TITLE
Include text box, see if results are different

### ISSUE THREAD

**Issue by pkolo** [AlexGio18/articulate-final-project#11]
* Test on backend to see if worthwhile first

**Comment by babiesinspace** [comment]
- transcript of speech to compare results
- Create an algorithm to see differentials?

**Comment by babiesinspace** [comment]
@AlexGio18 Looking into this.

Notes: Perhaps you can do entirely on the front? Only the text from the text box or the transcript from the recording needs to be persisted or sent to the API at first.. Can address sending both to the API separately later down the road to get comparison data. At first lets just compare the two and show the user how clearly they're speaking?
