### ISSUE TITLE
'Try Again Prompt' should display if there is not enough information

### ISSUE THREAD

**Issue by AlexGio18** [AlexGio18/articulate-final-project#144]
Right now if someone speaks into the microphone and speaks for a short time and stops the recording, sometimes there is not enough information to display emotional data and keywords and heirarchy. Maybe we should only display results with enough information, like if there is atleast one keyword. Not sure if this can be a quick fix on the back end, but we could do this on the front end.

**Comment by pkolo** [comment]
#159
