### ISSUE TITLE
Guest User functionality

### ISSUE THREAD

**Issue by pkolo** [AlexGio18/articulate-final-project#39]

**Comment by babiesinspace** [comment]
Starting to look into this

**Comment by babiesinspace** [comment]
- followed this wiki: https://github.com/plataformatec/devise/wiki/How-To:-Create-a-guest-user

Throwing an error : "NoMethodError (undefined method `[]' for nil:NilClass):"

Tomorrow going to try researching the gem CANCANCAN to define user & guest privileges

**Comment by babiesinspace** [comment]
#80

Still possibly buggy. Needs more testing
