### ISSUE TITLE
Confident score in doc_language_tone is always 0

### ISSUE THREAD

**Issue by pkolo** [AlexGio18/articulate-final-project#54]

**Comment by babiesinspace** [comment]
SQL (0.5ms)  INSERT INTO "doc_language_tones" ("analytical", "confident", "tentative", "speech_result_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["analytical", 0.065036], **["confident", 0.668884],** ["tentative", 0.0], ["speech_result_id", 5], ["created_at", 2017-01-16 02:57:29 UTC], ["updated_at", 2017-01-16 02:57:29 UTC]]

**Comment by babiesinspace** [comment]
Sample: "You can also directly input the transcript of your speech here." (From the text box)

**Comment by pkolo** [comment]
cool. i suspected it might have just been a coincidence, thanks for confirming!
