### ISSUE TITLE
Average Stats in History

### ISSUE THREAD

**Issue by babiesinspace** [AlexGio18/articulate-final-project#87]
-User can see average stats in their homepage or history page
- (Top keywords, Average lan. tones/social/emotional)

**Comment by AlexGio18** [comment]
Currently Working

**Comment by babiesinspace** [comment]
#96 <-- @AlexGio18 created pull request. Possibly easier to render the json if this is mixed in as a module? Must test both in console and on history page

**Comment by AlexGio18** [comment]
Each user has an average for social tones, language tones, emotional tones, and wpm. Should we add more or close this issue?

**Comment by pkolo** [comment]
#105
